name: NPQplugin
main: Eriol_Eandur.npq_plugin.NPQPlugin
version: 1.0
description: New Player Quiz Plugin
load: POSTWORLD
depend: [Multiverse-Core]
commands:
    reloadnpq:
        description: reloads New player Quiz
        usage: /reloadnpq [filename]
    debugnpq:
        description: shows debug informations
        usage: /debugnpq [world|here]
permissions:
    npquiz.staff:
        default: op
        children:
            npquiz.user: true
    npquiz.user:
        default: true