name: NewPlayerQuiz
main: com.mcmiddleearth.newPlayerQuiz.NewPlayerQuizPlugin
version: 1.0
description: New Player Quiz Plugin
load: POSTWORLD
depend: [Multiverse-Core]
commands:
    npq:
        description: manages new player quiz
        usage: /npq load|debug|delay
permissions:
    newplayerquiz:
        default: true
