name: NewPlayerQuiz
main: com.mcmiddleearth.newPlayerQuiz.NewPlayerQuizPlugin
version: 1.0.2_delag
description: New Player Quiz Plugin
load: POSTWORLD
depend: [Multiverse-Core,PluginUtils]

commands:
    npq:
        description: manages new player quiz
        usage: /npq load|debug|delay
permissions:
    npq.user:
        default: true
    npq.admin: 
        default: op
