name: NPQplugin
main: Eriol_Eandur.npq_plugin.NPQPlugin
version: 0.1
description: New Player Quiz Plugin
commands:
    reloadnpq:
        description: reloads New player Quiz
        usage: TBA
permissions:
    npquiz.staff:
        default: op
        children:
            npquiz.user: true
    npquiz.user:
        default: true