name: NewPlayerQuiz
main: com.mcmiddleearth.newPlayerQuiz.NewPlayerQuizPlugin
version: 1.1
description: New Player Quiz Plugin
load: POSTWORLD
depend: [Multiverse-Core,PluginUtils]
api-version: 1.13

commands:
    npq:
        description: manages new player quiz
        usage: /npq load|debug|delay
permissions:
    npq.user:
        default: true
    npq.admin: 
        default: op
